### ISSUE TITLE
Bad code generation when specifying format type 'date-time'

### ISSUE THREAD

**Issue by jkoutavas** [aws/aws-sdk-cpp#914]
### What platform/OS are you using?

macOS

### What compiler are you using? what version?

Xcode 9.4

### What's your CMake arguments?

cmake -DBUILD_ONLY="core;cognito-identity;cognito-idp" -DADD_CUSTOM_CLIENTS="serviceName={my-custom-service}, version=2018-07-19" -DMINIMIZE_SIZE=ON -DBUILD_SHARED_LIBS=OFF -DSIMPLE_INSTALL=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET="10.11" -DCPP_STANDARD=17 .

### Can you provide a TRACE level log? (sanitize any sensitive information)

Doesn't apply.

### Issue

{my-custom-service} has swagger.yaml containing this:

```
  MyThing:
    required:
      - datetime
    properties:
      datetime:
        type: string
        format: date-time
        description: The ISO8601 date-time of when MyThing was posted
```

The generated `model/MyThing.cpp` code has this, which will SIGABRT upon execution of ` m_datetime = jsonValue.GetDouble()`:

```
MyThing& MyThing::operator =(const JsonValue& jsonValue)
{
  if(jsonValue.ValueExists("datetime"))
  {
    m_datetime = jsonValue.GetDouble("datetime");

    m_datetimeHasBeenSet = true;
  }
```

`m_datetime` is declared as `Aws::Utils::DateTime`
